CREATE DATABASE hashs;

USE hashs;

CREATE TABLE md5 (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(256),
	senha VARCHAR(32)
);

CREATE TABLE sha1 (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(256),
	senha VARCHAR(40)
);

CREATE TABLE bcrypt (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(256),
	senha VARCHAR(256)
);